export const GESTION_TAREA_ESTADOS = Object.freeze({
  PENDIENTE: "PENDIENTE",
  EN_CURSO: "EN_CURSO",
  EN_REVISION: "EN_REVISION",
  FINALIZADA: "FINALIZADA",
  CANCELADA: "CANCELADA",
});

export const GESTION_PROYECTO_ESTADOS = Object.freeze({
  BORRADOR: "BORRADOR",
  ACTIVO: "ACTIVO",
  PAUSADO: "PAUSADO",
  FINALIZADO: "FINALIZADO",
  CANCELADO: "CANCELADO",
});

export const GESTION_TRANSICIONES_TAREA = Object.freeze({
  PENDIENTE: ["EN_CURSO", "CANCELADA"],
  EN_CURSO: ["EN_REVISION", "CANCELADA"],
  EN_REVISION: ["FINALIZADA", "EN_CURSO", "CANCELADA"],
  FINALIZADA: [],
  CANCELADA: [],
});

export const GESTION_ACTIVIDAD_TIPOS = Object.freeze({
  COMENTARIO: "COMENTARIO",
  CAMBIO_ESTADO: "CAMBIO_ESTADO",
  ASIGNACION: "ASIGNACION",
  CHECKLIST: "CHECKLIST",
  SISTEMA: "SISTEMA",
});

export const GESTION_ROLES_PARTICIPANTE = Object.freeze({
  PARTICIPANTE: "PARTICIPANTE",
  OBSERVADOR: "OBSERVADOR",
  REVISOR: "REVISOR",
});

export const GESTION_ROLES_PROYECTO = Object.freeze({
  RESPONSABLE: "RESPONSABLE",
  COLABORADOR: "COLABORADOR",
  OBSERVADOR: "OBSERVADOR",
  SUPERVISOR: "SUPERVISOR",
});

export const GESTION_ESTADOS_TAREA = Object.freeze({
  PENDIENTE: "PENDIENTE",
  EN_CURSO: "EN_CURSO",
  EN_REVISION: "EN_REVISION",
  FINALIZADA: "FINALIZADA",
  CANCELADA: "CANCELADA",
});

export const GESTION_TRANSICIONES = Object.freeze({
  PENDIENTE: ["EN_CURSO", "CANCELADA"],
  EN_CURSO: ["EN_REVISION", "CANCELADA"],
  EN_REVISION: ["FINALIZADA", "EN_CURSO", "CANCELADA"],
  FINALIZADA: [],
  CANCELADA: [],
});

export const GESTION_TIPOS_ACTIVIDAD = Object.freeze({
  SISTEMA: "SISTEMA",
  COMENTARIO: "COMENTARIO",
  CAMBIO_ESTADO: "CAMBIO_ESTADO",
  CHECKLIST: "CHECKLIST",
  ASIGNACION: "ASIGNACION",
});
