export const GESTION_PRIORIDADES = Object.freeze({
  BAJA: "BAJA",
  NORMAL: "NORMAL",
  ALTA: "ALTA",
  CRITICA: "CRITICA",
});

export const GESTION_TIPOS_TAREA = Object.freeze({
  OPERATIVA: "OPERATIVA",
  CONTROL: "CONTROL",
  APROBACION: "APROBACION",
  INCIDENCIA: "INCIDENCIA",
  MEJORA: "MEJORA",
  DOCUMENTACION: "DOCUMENTACION",
  REUNION: "REUNION",
  ERP_AUTOMATICA: "ERP_AUTOMATICA",
});
