export const GESTION_EVENTOS = Object.freeze({
  INSPECCION_RECHAZADA: "INSPECCION_RECHAZADA",
  HALLAZGO_GENERADO: "HALLAZGO_GENERADO",
  INSPECCION_VENCIDA: "INSPECCION_VENCIDA",

  PAGO_PROXIMO_VENCER: "PAGO_PROXIMO_VENCER",
  PAGO_VENCIDO: "PAGO_VENCIDO",
  DIFERENCIA_CAJA: "DIFERENCIA_CAJA",

  DOCUMENTO_VENCIDO: "DOCUMENTO_VENCIDO",
  DOCUMENTO_POR_VENCER: "DOCUMENTO_POR_VENCER",
  PROCEDIMIENTO_SIN_REVISION: "PROCEDIMIENTO_SIN_REVISION",

  OT_CRITICA_VENCIDA: "OT_CRITICA_VENCIDA",
  EQUIPO_FUERA_SERVICIO: "EQUIPO_FUERA_SERVICIO",
  MANTENIMIENTO_PENDIENTE: "MANTENIMIENTO_PENDIENTE",

  LIQUIDACION_PENDIENTE: "LIQUIDACION_PENDIENTE",
  RECIBO_NO_CONFIRMADO: "RECIBO_NO_CONFIRMADO",
  NOVEDAD_PENDIENTE: "NOVEDAD_PENDIENTE",

  TAREA_CREADA: "TAREA_CREADA",
  TAREA_ASIGNADA: "TAREA_ASIGNADA",
  TAREA_ESTADO_CAMBIADO: "TAREA_ESTADO_CAMBIADO",
  TAREA_VENCIDA: "TAREA_VENCIDA",
  TAREA_BLOQUEADA: "TAREA_BLOQUEADA",
  REVISION_DEMORADA: "REVISION_DEMORADA",
  PROYECTO_RIESGO: "PROYECTO_RIESGO",
});

export const GESTION_ACCIONES_AUTOMATIZACION = Object.freeze({
  CREAR_TAREA: "CREAR_TAREA",
  CREAR_PROYECTO: "CREAR_PROYECTO",
  CREAR_ALERTA_CSI: "CREAR_ALERTA_CSI",
  ENVIAR_NOTIFICACION: "ENVIAR_NOTIFICACION",
  ENVIAR_EMAIL: "ENVIAR_EMAIL",
  GENERAR_RECORDATORIO: "GENERAR_RECORDATORIO",
  ESCALAR_SUPERVISOR: "ESCALAR_SUPERVISOR",
  ESCALAR_GERENCIA: "ESCALAR_GERENCIA",
});
