export const EVENTOS_EVALUACION = {
    // Eventos de negocio
    RESPUESTA_REGISTRADA: "RESPUESTA_REGISTRADA",
    RESULTADO_CALCULADO: "RESULTADO_CALCULADO",

    // Eventos de notificación
    ALERTA_ROJA: "ALERTA_ROJA",
    BANDERA_CRITICA: "BANDERA_CRITICA",
    CAIDA_RENDIMIENTO: "CAIDA_RENDIMIENTO",
    BAJA_PARTICIPACION: "BAJA_PARTICIPACION",
    DNI_NO_RECONOCIDO: "DNI_NO_RECONOCIDO",
    RESUMEN_SEMANAL: "RESUMEN_SEMANAL",
    RESUMEN_MENSUAL: "RESUMEN_MENSUAL",
    RECORDATORIO_SUPERVISIONES: "RECORDATORIO_SUPERVISIONES",
    CAIDA_RENDIMIENTO: "CAIDA_RENDIMIENTO",

    MEJORA_RENDIMIENTO: "MEJORA_RENDIMIENTO",

    ESTABILIDAD_RENDIMIENTO: "ESTABILIDAD_RENDIMIENTO",


    COMPETENCIA_CRITICA:
        "COMPETENCIA_CRITICA",

    AUTOEVALUACION_DESALINEADA:
        "AUTOEVALUACION_DESALINEADA",

    SUPERVISION_DESALINEADA:
        "SUPERVISION_DESALINEADA",

    CONSENSO_EVALUACION:
        "CONSENSO_EVALUACION",

    RIESGO_BAJO: "RIESGO_BAJO",

    RIESGO_MEDIO: "RIESGO_MEDIO",

    RIESGO_ALTO: "RIESGO_ALTO",

    RIESGO_CRITICO: "RIESGO_CRITICO",
    TENDENCIA_POSITIVA: "TENDENCIA_POSITIVA",

    TENDENCIA_NEGATIVA: "TENDENCIA_NEGATIVA",

    MEJORA_SOSTENIDA: "MEJORA_SOSTENIDA",

    CAIDA_SOSTENIDA: "CAIDA_SOSTENIDA",

    ESTABILIDAD: "ESTABILIDAD",
    
};

export const CONFIGURACION_POR_EVENTO = {

    ALERTA_ROJA: "alerta_roja",

    BANDERA_CRITICA: "bandera_critica",

    CAIDA_RENDIMIENTO: "caida_rendimiento",

    MEJORA_RENDIMIENTO: "mejora_rendimiento",

    COMPETENCIA_CRITICA: "competencia_critica",

    AUTOEVALUACION_DESALINEADA: "autoevaluacion_desalineada",

    CAIDA_SOSTENIDA: "caida_sostenida",

    MEJORA_SOSTENIDA: "mejora_sostenida",

    TENDENCIA_NEGATIVA: "tendencia_negativa",

    TENDENCIA_POSITIVA: "tendencia_positiva",

    ESTABILIDAD: "estabilidad",

    CONSENSO_EVALUACION: "consenso_evaluacion",

    RIESGO_BAJO: "riesgo_bajo",

    RIESGO_MEDIO: "riesgo_medio",

    RIESGO_ALTO: "riesgo_alto",

    RIESGO_CRITICO: "riesgo_critico",

    BAJA_PARTICIPACION: "baja_participacion",

    RESUMEN_SEMANAL: "resumen_semanal",

    RESUMEN_MENSUAL: "resumen_mensual",

    RECORDATORIO_SUPERVISIONES:
        "recordatorio_supervisiones",

    DNI_NO_RECONOCIDO:
        "dni_no_reconocido"

};